distributed.nanny - INFO -         Start Nanny at: 'tcp://128.211.146.185:45157'
distributed.nanny - INFO - Closing Nanny at 'tcp://128.211.146.185:45157'
distributed.nanny - WARNING - Worker process still alive after 0 seconds, killing
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/home/yang1452/.local/lib/python3.7/site-packages/distributed/core.py", line 275, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/home/yang1452/.conda/envs/cent7/5.3.1-py37/hmumu/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yang1452/.conda/envs/cent7/5.3.1-py37/hmumu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yang1452/.conda/envs/cent7/5.3.1-py37/hmumu/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yang1452/.local/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 466, in <module>
    go()
  File "/home/yang1452/.local/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 462, in go
    main()
  File "/home/yang1452/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yang1452/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yang1452/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yang1452/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yang1452/.local/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 448, in main
    loop.run_sync(run)
  File "/home/yang1452/.local/lib/python3.7/site-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/home/yang1452/.local/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 442, in run
    await asyncio.gather(*nannies)
  File "/home/yang1452/.conda/envs/cent7/5.3.1-py37/hmumu/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/yang1452/.local/lib/python3.7/site-packages/distributed/core.py", line 281, in _
    type(self).__name__, timeout
concurrent.futures._base.TimeoutError: Nanny failed to start in 60 seconds
